### ISSUE TITLE
改進建議－默認設定、記住選項、方案選單、載入速度、群組指南

### ISSUE THREAD

**Issue by cuichungman** [LibreService/my_rime#18]
Qijia 你好，
　　
感謝作者持續維護並不斷提升線上版 Rime。自上次反饋以來，My Rime 喺 Google 嘅搜尋中已有明顯嘅前置，十分便利。今再用時，有若干發現同諗法，望作者關注。
　　
　　
**【初次訪問時嘅默認設定】**
![初始狀態](https://github.com/LibreService/my_rime/assets/16935971/55cdad3f-0ca2-4da8-b25e-c06093dfce72)
留意到喺用户初始訪問現有嘅兩個粵語輸入法時，會默認以簡體字輸出（請見上圖選項欄位）。建議考慮為現已知之語言／輸入法嘅常用習慣固定初始訪問所提供嘅默認選項。鑑於粵文常以傳統漢字呈現，請作者為各粵語輸入法默認以傳統漢字輸出。
　　
　　
**【記錄用戶設定】**
![右側選項未能記住](https://github.com/LibreService/my_rime/assets/16935971/3c72a7bb-3f52-4eff-be0c-fac89b6139e7)
記得之前向作者提過希望 My Rime 可以記住用户選項，作者好快脆就完成咗**記住用户最後選取嘅輸入法**及**正／簡漢字**呢兩項，感謝作者大大嘅效率。惟尚有**全／半形**及**表情**等幾個位於工具欄右側嘅選項未能被記住，呢方面亦希望作者完善。
　　
　　
**【方案選單分類】**
![選單分類](https://github.com/LibreService/my_rime/assets/16935971/e95b4100-6750-4017-8afc-b1ad82f62ea2)
發現方案選單現已為不同輸入法劃分咗類別，便於用户檢索。惟見選單以**音碼、方言、雙拼、形碼、音標、並擊、古音**分類嘅方式略為怪異，分類標籤層級不劃一，使方案／輸入法未能得到正確擠放。例如，將可被「音碼」包含嘅「方言」「雙拼」同「古音」並列，導致分類混亂，亦會惹嚟爭議。
　　
故此，就住呢個情況提供兩個完善方案供作者參考：
　　
一、建議作者設計以兩個選單供用户篩選——第一選單提供「音碼」「形碼」及「其它」，而第二選單則因應第一選單嘅選取，提供直達目的方案嘅分類。如，音碼分類：全拼、雙拼、三拼、古音等；形碼分類：倉頡、速成、五筆等。
　　
_舉例，「粵語雙拼」方案將位於：音碼 ➝ 雙拼 ➝ 粵語雙拼_；
　　
二、若作者鍾意只有一個選單，則建議將分類改善得更為具體，如「音碼－全拼」「音碼－雙拼」「音碼－三拼」「音碼－注音」等等，使分類歸於同一層級上。
　　
_舉例，「粵語雙拼」方案將位於：音碼－雙拼 ➝ 粵語雙拼_；
　　
作出以上改善，亦有益於未來更多輸入方案加入後嘅整理。
　　
　　
**【方案載入速度】**
![載入速度](https://github.com/LibreService/my_rime/assets/16935971/43f754e3-bf0e-4110-849d-d3d454edaed1)
不知為何，近期方案載入嘅速度似乎較 My Rime 建立初期慢咗唔少。喺選單選取輸入法後，有時會轉圈較長時間。雖不太影響使用，但未知呢個情況是否正常，故僅此提出，望作者得知。
　　
　　
**題外【輸入法／技術交流群組引流】**
就現時所知，Telegram 上有以下官方群組：
RIME：https://t.me/loverime
Rime-Cantonese：https://t.me/rime_cantonese
Rime 鼠须管 输入法：https://t.me/rimeim
Rime-Cantonese FAQ：https://t.me/rime_cantonese_faq
　　
作者不妨於 My Rime 頁面下方列出 Rime、My Rime 及／或各常用輸入法嘅交流群組（需大家繼續補充），以助用户揾到所需嘅技術支援。
　　
　　
知道作者事忙，本應長話短説，但性格不容許，還請作者見諒，亦多謝作者睇晒全篇反饋。感恩。
　　
　　
秋安，
　　
ＣＨＵＮＧ

**Comment by eagleoflqj** [comment]
### 粤语的默认变体
因为粤语区除了香港还有广东，广东既然在大陆那使用简体字的需求也是有的，见#11。
可行的改进方式是，像#15 那样，根据浏览器locale设定默认值

Fixed by: 

### 记录其他选项
好的。

Fixed by: 

### 方案分类
这个最近引起的争论不少，考虑到My RIME并不希望做成一个中央式的服务让所有人都来my-rime.vercel.app这个网站，而是鼓励其他人（不论出于何种目的）fork并自行部署以推广自己的输入方案，可以认为这个仓库只是所有My RIME fork中的一个（像不像汉语和下辖各个方言的关系？），仅代表这个fork所有者的偏好。因此，每个人都不必要求其他人的fork符合自己的习惯。
F4/Ctrl+`已经支持了，完全不想要分类的话可以无视那个下拉菜单，用RIME经典的候选框形式的方案选单。
暂不打算加入更多方案，因为这些方案都是预部署的（这样用户不需要部署），维护是有成本的，因此我只打算支持RIME官方方案。

Won't do.

### 加载时间
这个取决二进制词典的大小（以粤拼为例，[27M](https://www.npmjs.com/package/@rime-contrib/cantonese?activeTab=code)），以及你的网络环境连接jsdelivr CDN的速度。

Not applicable.

### 群组引流
Rime-Cantonese是妥妥的涉政群组，我既无意干涉，也不会将我这一fork的用户导向那里。当然，其他fork可以自由引流到任何地方。
其他群组也并不是纯粹的技术交流群组，所以我都不打算引流，包括我自己的LibreService Discord群，可以在https://github.com/LibreService 看见但不会进我的代码里。

Won‘t do.

**Comment by cuichungman** [comment]
### **【初次訪問時嘅默認設定】**
多謝指出。了解到中國方面嘅用户有簡體字嘅需求，亦應得到照顧。作者大大所及之「根据浏览器locale设定默认值」係一個更優秀嘅改進方式，感謝大大周全嘅考慮。

### **【記錄用戶設定】**
多謝大大接納。感恩

### **【方案選單分類】**
已留意到用户喺 #17 中嘅討論，當中各用户論點皆不無道理，呢個確係漢語界嘅長期問題。即使撇除本反饋中所指出「將可被『音碼』包含嘅『方言』『雙拼』同『古音』並列」所帶嚟嘅層級錯亂，使用「方言」一詞亦不難遇見其將會惹嚟嘅爭議。

關於呢個情況，想講下自己嘅睇法：粵語屬語言層級，而廣州話屬粵語下嘅一個分支同時亦作為粵語嘅通用音，在此理解下，將以廣州話為標準音嘅粵語輸入法置於「方言」分類下本無大礙。惟目前「方言」一詞喺中國語境下，遭到一定程度嘅貶抑同負面渲染，維持該詞嘅運用就似乎「有點兒那個」嘞。舉個令人印象深刻嘅例子：「支那」一詞原本亦非負面，但經過歷史戰爭嘅使用及如今神劇嘅渲染後，該詞已變得「傷害民族感情」。可見，儘管「支那」「方言」等詞彙本無負面意味，但喺社會現實中，其已在一定程度上與大眾嘅負面觀感產生捆綁。

設身處地噉諗：儘管理性上不認為「支那」一詞有問題，但感情上終歸不願被「支那」前「支那」後噉稱呼；同樣，儘管理性上不認為「方言」一詞有問題，但感情上見到自己嘅語言被標籤為「方言」確會令人感到不是滋味。

身為粵語使用者，固然希望作者稍為調整一下該稱呼。或者使用「其他漢語」可會更佳？大大不妨考慮。

### **【方案載入速度】**
多謝大大指出。原來係自己嘅網速問題，喊喊　😭

### **【輸入法／技術交流群組引流】**
理解嘅。明白大大嘅擔憂。喺 Rime 社群打滾多年，不難觀察到，用得 Rime 嘅，為數不少係有理想、有要求、思想上較為進步嘅朋友，大家喺對社會發展方向上有更出眾嘅見解亦不出意外。

多謝坦言，亦尊重大大嘅選擇　🫡

**Comment by cuichungman** [comment]
感謝大大接納建議 🤗

在 2023年7月26日週三 下午9:40，Qijia Liu ***@***.***> 寫道：
